dateModified: 1657272876
email:
  fromEmail: remco@chilli.be
  fromName: 'Craft Starter'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    543cfeaf-eb82-4a05-beb8-575f1a80a2ff: Common # Common
    57884dad-cf02-49d0-b284-96a096a41e34: $SYSTEM_NAME # $SYSTEM_NAME
    ebc783a1-3db3-42fb-8f2a-c108aed8b086: 'Craft Starter' # Craft Starter
system:
  edition: pro
  live: true
  name: 'Craft Starter'
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
